package buddy.dto;

import java.util.Date;

/**
 * REPLY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Reply {
	/** REPLY_NO. */
	private Integer replyNo;

	/** BOARD. */
	private Board board;

	/** BUDDY. */
	private Buddy buddy;

	/** REPLY_CONTENT. */
	private String replyContent;

	/** REG_DATE. */
	private Date regDate;

	/**
	 * 생성자.
	 */
	public Reply() {
	}

	public Reply(int replyNo, int commentNo, String buddyId, String replyContent, Date regDate) {
		this.replyNo = replyNo;
		this.board = new Board(commentNo);
		this.buddy = new Buddy(buddyId);
		this.replyContent = replyContent;
		this.regDate = regDate;
	}

	public Reply(int commentNo, String buddyId, String replyContent) {
		this(0, commentNo, buddyId, replyContent, null);
	}

	public Reply(String buddyId, String replyContent, Date regDate) {
		this(0, 0, buddyId, replyContent, regDate);
	}
	public Reply(int replyNo, String replyContent) {
		this(replyNo, 0, null, replyContent, null);
	}
	/**
	 * REPLY_NO을 설정합니다..
	 * 
	 * @param replyNo
	 *            REPLY_NO
	 */
	public void setReplyNo(Integer replyNo) {
		this.replyNo = replyNo;
	}

	/**
	 * REPLY_NO을 가져옵니다..
	 * 
	 * @return REPLY_NO
	 */
	public Integer getReplyNo() {
		return this.replyNo;
	}

	/**
	 * BOARD을 설정합니다..
	 * 
	 * @param board
	 *            BOARD
	 */
	public void setBoard(Board board) {
		this.board = board;
	}

	/**
	 * BOARD을 가져옵니다..
	 * 
	 * @return BOARD
	 */
	public Board getBoard() {
		return this.board;
	}

	/**
	 * BUDDY을 설정합니다..
	 * 
	 * @param buddy
	 *            BUDDY
	 */
	public void setBuddy(Buddy buddy) {
		this.buddy = buddy;
	}

	/**
	 * BUDDY을 가져옵니다..
	 * 
	 * @return BUDDY
	 */
	public Buddy getBuddy() {
		return this.buddy;
	}

	/**
	 * REPLY_CONTENT을 설정합니다..
	 * 
	 * @param replyContent
	 *            REPLY_CONTENT
	 */
	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	/**
	 * REPLY_CONTENT을 가져옵니다..
	 * 
	 * @return REPLY_CONTENT
	 */
	public String getReplyContent() {
		return this.replyContent;
	}

	/**
	 * REG_DATE을 설정합니다..
	 * 
	 * @param regDate
	 *            REG_DATE
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * REG_DATE을 가져옵니다..
	 * 
	 * @return REG_DATE
	 */
	public Date getRegDate() {
		return this.regDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((replyNo == null) ? 0 : replyNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Reply other = (Reply) obj;
		if (replyNo == null) {
			if (other.replyNo != null) {
				return false;
			}
		} else if (!replyNo.equals(other.replyNo)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Reply [replyNo=" + replyNo + ", board=" + board + ", buddy=" + buddy + ", replyContent=" + replyContent
				+ ", regDate=" + regDate + "]";
	}

}
